baseurl: http://www.precheck.site/
#baseurl: https://crsuzh.github.io/Precheck/
languageCode: en-us
title: "PRECHECK: A checklist to evaluate COVID-19 preprints"
subtitle: Project website
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  posts: /:year/:month/:day/:slug/
menu:
  main:
    - name: Checklist-PDF
      url: https://osf.io/q98wa/
    - name: Team
      url: /team/
    - name: About
      url: /about/
    - name: Checklist
      url: /the_checklist/
    - name: OSF Project
      url: https://osf.io/nk4ta/
    #- name: OSF Project Page
    #  url: https://osf.io/nk4ta/
    #- name: Twitter
    #  url: https://twitter.com/swissrn
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: precheck.png
    width: 50
markup:
  goldmark:
    renderer:
      unsafe: true